services:
  auth-service:
    build:
      context: ./auth_service
    container_name: auth-service
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017  # Fix to match service name
    depends_on:
      - mongodb
    command: ["sh", "-c", "./wait-for-it.sh mongodb 27017 -- uvicorn main:app --host 0.0.0.0 --port 8000"]

  user-service:
    build:
      context: ./user_service
    container_name: user-service
    ports:
      - "8001:8001"
    environment:
      - SECRET_KEY=your_secret_key
    depends_on:
      - auth-service

  chat-service-1:
    build:
      context: ./chat_service
    ports:
      - "8002:8002"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/chatdb
      - SECRET_KEY=your_secret_key
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  chat-service-2:
    build:
      context: ./chat_service
    ports:
      - "8003:8002"
    environment:
      - MONGO_URI=mongodb://mongodb:27017/chatdb
      - SECRET_KEY=your_secret_key
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq

  mongodb:
    image: mongo:5.0
    container_name: mongodb
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
      - ./init-mongo:/docker-entrypoint-initdb.d
    environment:
      - MONGO_INITDB_DATABASE=chat_app

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth-service
      - user-service
      - chat-service-1
      - chat-service-2

  chat-consumer:
    build:
      context: ./chat_service          # reuse the same image
    container_name: chat-consumer
    environment:
      - MONGO_URI=mongodb://mongodb:27017/chatdb
      - RABBITMQ_HOST=rabbitmq
    depends_on:
      - rabbitmq
      - mongodb
    command: ["python", "-u", "messaging/consumer.py"]
    restart: unless-stopped  


  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"       # AMQP protocol (used by your services)
      - "15672:15672"     # Management UI (http://localhost:15672)
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  mongo_data:
