services:
  auth-service:
    build:
      context: ./auth_service
    container_name: auth-service
    ports:
      - "8000:8000"
    environment:
      - MONGO_URL=mongodb://mongo:27017
    depends_on:
      - mongo

  user-service:
    build:
      context: ./user_service
    container_name: user-service
    ports:
      - "8001:8001"
    depends_on:
      - auth-service
    environment:
      - SECRET_KEY=your_secret_key

  chat-service:
    build:
      context: ./chat_service
    container_name: chat-service
    ports:
      - "8002:8002"
    environment:
      - SECRET_KEY=your_secret_key
    depends_on:
      - auth-service

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db

  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "8080:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - auth-service
      - user-service
      - chat-service

volumes:
  mongo-data:
